### ISSUE TITLE
Expected hash or Mixin instance, got [object Undefined]

### ISSUE THREAD

**Issue by amedrz** [ivanvotti/ember-cli-pusher#1]
Hi guys,

I'm using ember-cli 0.1.15 and just can't get this working,  this is my controller:

````
`import Ember from 'ember'`
`import Bindings from 'ember-pusher/bindings'`

ApplicationController = Ember.Controller.extend(Bindings,
  PUSHER_SUBSCRIPTIONS: {
    channelOne: ['channel-one']
  }

  actions: (
    eventOne: (->
      console.log "eventOne"
    )
  )
)
````

And when I try to load the page I get this exception:
````
Error while processing route: foo Assertion Failed: Expected hash or Mixin instance, got [object Undefined]
````

Any idea what's going on?

**Comment by ivanvotti** [comment]
What if you try to import it like this?
```
`import { Bindings } from 'ember-pusher/bindings'`
```

**Comment by amedr** [comment]
@ivanvotti it worked! Thanks. Whats the difference between using key braces or not?

**Comment by elskwid** [comment]
@amedrz the [`ember-pusher/bindings`](https://github.com/jamiebikies/ember-pusher/blob/master/lib/ember-pusher/bindings.js#L33) file exports a named binding, which is used for multiple exports per module so on the import side you have to specify which one you want to import. Hope this helps. (Dig deeper here: http://www.2ality.com/2014/09/es6-modules-final.html).

**Comment by amedrz** [comment]
@elskwid thanks for the clarification :)
