### ISSUE TITLE
Deprecation request

### ISSUE THREAD

**Issue by jamiebikies** [ivanvotti/ember-cli-pusher#13]
Hi! I was hoping you might be able to do a deprecation of the `ember-cli-pusher` module as the main repo is now an Ember module....

`npm deprecate ember-cli-pusher`

I was also hoping you could unlist the bower module since you've taken the real name of the package `ember-pusher`....

https://github.com/bower/bower/issues/120
`curl -X DELETE "https://bower.herokuapp.com/packages/ember-pusher?access_token=TOKEN"`

where TOKEN is a github personal access token.

If you need a hand with anything, let me know!

**Comment by ivanvotti** [comment]
Hi. It's done. Just in case, I added you as a maintainer of `ember-cli-pusher` npm package. I personally don't use it anymore, but some people might do. So feel free to do anything with the npm package to make the transition to ember-pusher for them better.

**Comment by jamiebikies** [comment]
Thanks Ivan!
