### ISSUE TITLE
Initializer not running

### ISSUE THREAD

**Issue by melindaweathers** [ivanvotti/ember-cli-pusher#5]
Thank you for putting together ember-cli-pusher. The base ember-pusher has been working great in my application for over a year now. However, I am now migrating this application to ember-cli, and having trouble with using it as ember-cli-pusher. I am on ember-cli 2.2, and I followed the install:addon and import steps you listed.

It appears that the initializer in the addon is not running. The symptom that affects me is that I cannot do this.get('pusher') in my controllers since it was never injected into the controllers (since that was supposed to happen in the initializer).

It's very possible that I have done something wrong, but I wanted to see if anyone else has had this problem, or whether there is another step required to get the initializer loaded now. Thanks!

**Comment by melindaweathers** [comment]
As you might have guessed, this was some kind of error I was having with ember-cli, not related to ember-cli-pusher in particular.

**Comment by ChrisDrit** [comment]
@melindaweathers - i am currently have the same issue, what was your issue with ember-cli and how did you overcome it? Thanks!
